<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wacon_cookie_management"
 *
 * Auto generated by Extension Builder 2019-09-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Wacon Cookie Management',
    'description' => 'Verschiedene Cookies können individuell zugelassen werden. Unterscheidung in notwendige und optionale Cookies',
    'category' => 'plugin',
    'author' => 'Kerstin Schmitt',
    'author_email' => 'info@wacon.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
